import type {
  FullReport,
  StoredComment,
  ThemeGroup,
  VideoMeta,
} from "./schema";

export type ExportPayload = {
  video: VideoMeta;
  report: FullReport;
  comments: StoredComment[];
};

export type ExportFormat = "html" | "markdown" | "txt" | "json" | "csv" | "sheets";

function pct(n: number): string {
  return `${Math.round(n)}%`;
}

function shortDate(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? "" : d.toISOString().slice(0, 10);
}

function evidenceLines(comments: StoredComment[], max = 4): string[] {
  return comments.slice(0, max).map((c) => {
    const meta = `👍 ${c.likeCount}${shortDate(c.publishedAt) ? ` · ${shortDate(c.publishedAt)}` : ""}`;
    return `    - ${c.author} (${meta})\n      "${c.text.replace(/\s+/g, " ").trim()}"`;
  });
}

function themeLines(items: ThemeGroup[]): string[] {
  if (!items.length) return ["- (none detected)"];
  const out: string[] = [];
  for (const t of items) {
    out.push(`- ${t.theme} — ${t.mentionCount} mention${t.mentionCount === 1 ? "" : "s"}`);
    out.push(...evidenceLines(t.comments));
  }
  return out;
}

const SECTIONS: { key: keyof FullReport; label: string }[] = [
  { key: "positiveFeedback", label: "Positive Feedback" },
  { key: "criticism", label: "Criticism" },
  { key: "episodeRequests", label: "Episode Requests" },
  { key: "hostFeedback", label: "Host Feedback" },
  { key: "editingFeedback", label: "Editing Feedback" },
  { key: "thumbnailFeedback", label: "Thumbnail Feedback" },
  { key: "titleFeedback", label: "Title Feedback" },
  { key: "sponsorFeedback", label: "Sponsor Feedback" },
  { key: "recurringTopics", label: "Recurring Topics" },
];

export function toMarkdown({ video, report }: ExportPayload): string {
  const lines: string[] = [];
  lines.push(`# Community AI Report — ${video.title}`);
  lines.push("");
  lines.push(`**Channel:** ${video.channelTitle}  `);
  lines.push(`**Video:** ${video.url}  `);
  lines.push(`**Published:** ${video.publishedAt}  `);
  lines.push(
    `**Views:** ${video.viewCount.toLocaleString()} · **Likes:** ${video.likeCount.toLocaleString()} · **Comments analyzed:** ${report.totalComments.toLocaleString()} (${report.totalReplies.toLocaleString()} replies)  `,
  );
  lines.push(
    `**Sentiment:** ${report.sentiment.label} — ${pct(report.sentiment.positivePct)} positive / ${pct(report.sentiment.neutralPct)} neutral / ${pct(report.sentiment.negativePct)} negative  `,
  );
  lines.push(`**Confidence:** ${Math.round(report.confidence * 100)}%`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push(report.summary);
  lines.push("");

  if (report.topComment) {
    lines.push(`## Top Comment`);
    lines.push(
      `> ${report.topComment.text}\n> — ${report.topComment.author} · 👍 ${report.topComment.likeCount.toLocaleString()} · ${shortDate(report.topComment.publishedAt)}`,
    );
    lines.push("");
  }

  lines.push(`## Most Requested Future Episodes`);
  if (report.mostRequestedFutureEpisodes.length) {
    for (const e of report.mostRequestedFutureEpisodes) {
      lines.push(`### ${e.title} — ${e.mentionCount} mentions`);
      if (e.supporters.length) {
        lines.push(
          `- Top supporters: ${e.supporters
            .map((s) => `${s.author} (${s.commentCount})`)
            .join(", ")}`,
        );
      }
      lines.push(`- Representative comments:`);
      lines.push(...evidenceLines(e.comments));
    }
  } else {
    lines.push("- (none detected)");
  }
  lines.push("");

  for (const s of SECTIONS) {
    lines.push(`## ${s.label}`);
    lines.push(...themeLines(report[s.key] as ThemeGroup[]));
    lines.push("");
  }

  lines.push(`## Moderation Issues`);
  if (report.moderationIssues.length) {
    for (const m of report.moderationIssues) {
      lines.push(`- **${m.type}** — ${m.count}`);
      lines.push(...evidenceLines(m.comments));
    }
  } else {
    lines.push("- (none detected)");
  }
  lines.push("");

  lines.push(`## Action Items`);
  if (report.actionItems.length) {
    report.actionItems.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
  } else {
    lines.push("- (none)");
  }
  lines.push("");
  lines.push(`---`);
  lines.push(`_Generated by Community AI._`);
  return lines.join("\n");
}

export function toTxt(payload: ExportPayload): string {
  return toMarkdown(payload)
    .replace(/^#+\s*/gm, "")
    .replace(/\*\*/g, "")
    .replace(/^> ?/gm, "")
    .replace(/`/g, "");
}

export function toJson(payload: ExportPayload): string {
  return JSON.stringify(payload, null, 2);
}

function csvEscape(value: string | number | boolean | null): string {
  const s = value === null || value === undefined ? "" : String(value);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function toCsv({ comments }: ExportPayload): string {
  const header = [
    "comment_id",
    "parent_id",
    "author",
    "author_channel_id",
    "is_reply",
    "like_count",
    "published_at",
    "updated_at",
    "text_original",
  ];
  const rows = comments.map((c) =>
    [
      c.commentId,
      c.parentId ?? "",
      c.author,
      c.authorChannelId ?? "",
      c.isReply,
      c.likeCount,
      c.publishedAt,
      c.updatedAt,
      c.text.replace(/\s+/g, " ").trim(),
    ]
      .map(csvEscape)
      .join(","),
  );
  return [header.join(","), ...rows].join("\n");
}

function topTheme(items: ThemeGroup[]): string {
  if (!items.length) return "";
  const t = items[0];
  return `${t.theme} (${t.mentionCount})`;
}

/** Single tab-separated row for pasting into an existing Google Sheets tracker. */
export function toSheetsRow({ video, report }: ExportPayload): string {
  const cells = [
    new Date().toISOString().slice(0, 10),
    video.channelTitle,
    video.title,
    video.url,
    report.totalComments,
    report.sentiment.label,
    `${pct(report.sentiment.positivePct)}/${pct(report.sentiment.neutralPct)}/${pct(report.sentiment.negativePct)}`,
    `${Math.round(report.confidence * 100)}%`,
    report.mostRequestedFutureEpisodes
      .slice(0, 3)
      .map((e) => `${e.title} (${e.mentionCount})`)
      .join("; "),
    topTheme(report.criticism),
    topTheme(report.sponsorFeedback),
    topTheme(report.hostFeedback),
    topTheme(report.editingFeedback),
    report.moderationIssues.map((m) => `${m.type} (${m.count})`).join("; "),
    report.actionItems.slice(0, 5).join(" | "),
    report.summary.replace(/\s+/g, " ").trim(),
  ];
  return cells.map((c) => String(c).replace(/[\t\n\r]+/g, " ").trim()).join("\t");
}

export const SHEETS_HEADER = [
  "Date",
  "Channel",
  "Video Title",
  "Video URL",
  "Total Comments",
  "Sentiment",
  "Pos/Neu/Neg",
  "Confidence",
  "Top Episode Requests",
  "Top Criticism",
  "Top Sponsor Feedback",
  "Top Host Feedback",
  "Top Editing Feedback",
  "Moderation",
  "Action Items",
  "Summary",
].join("\t");

/* ------------------------------------------------------------------ */
/* Self-contained, offline HTML report (preserves the dropdown layout) */
/* ------------------------------------------------------------------ */

function esc(s: string | number | null | undefined): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatNum(n: number): string {
  return new Intl.NumberFormat("en-US").format(n || 0);
}

function htmlComment(c: StoredComment): string {
  const meta = `👍 ${formatNum(c.likeCount)}${
    shortDate(c.publishedAt) ? ` · ${esc(shortDate(c.publishedAt))}` : ""
  }`;
  return `<li class="cm">
    <div class="cm-head"><span class="cm-author">${c.isReply ? "↳ " : ""}${esc(c.author)}</span><span class="cm-meta">${meta}</span></div>
    <div class="cm-text">${esc(c.text.trim())}</div>
  </li>`;
}

function htmlThemeDetails(items: ThemeGroup[]): string {
  if (!items.length) return `<p class="muted">Nothing notable detected.</p>`;
  return items
    .map(
      (t) => `<details class="acc">
      <summary><span class="acc-label">${esc(t.theme)}</span><span class="pill">${formatNum(t.mentionCount)}</span></summary>
      <ul class="cm-list">${t.comments.map(htmlComment).join("")}</ul>
    </details>`,
    )
    .join("");
}

function themeCard(title: string, items: ThemeGroup[]): string {
  const total = items.reduce((s, i) => s + i.mentionCount, 0);
  return `<section class="card">
    <div class="card-head"><h3>${esc(title)}</h3><span class="pill">${formatNum(total)} mentions</span></div>
    ${htmlThemeDetails(items)}
  </section>`;
}

export function toHtml({ video, report, comments }: ExportPayload): string {
  const s = report.sentiment;

  const futureEpisodes = report.mostRequestedFutureEpisodes.length
    ? report.mostRequestedFutureEpisodes
        .map(
          (e, i) => `<details class="acc">
      <summary><span class="acc-label">${i + 1}. ${esc(e.title)}</span><span class="pill">${formatNum(e.mentionCount)} mentions</span></summary>
      ${
        e.supporters.length
          ? `<div class="sub">Top Supporters</div><div class="chips">${e.supporters
              .map(
                (sp) =>
                  `<span class="chip"><b>${esc(sp.author)}</b> ${sp.commentCount} comment${
                    sp.commentCount === 1 ? "" : "s"
                  }</span>`,
              )
              .join("")}</div>`
          : ""
      }
      <div class="sub">Representative Comments</div>
      <ul class="cm-list">${e.comments.map(htmlComment).join("")}</ul>
    </details>`,
        )
        .join("")
    : `<p class="muted">No specific episode requests detected.</p>`;

  const moderation = report.moderationIssues.length
    ? report.moderationIssues
        .map(
          (m) => `<details class="acc">
      <summary><span class="acc-label danger">${esc(m.type)}</span><span class="pill">${formatNum(m.count)}</span></summary>
      <ul class="cm-list">${m.comments.map(htmlComment).join("")}</ul>
    </details>`,
        )
        .join("")
    : `<p class="muted">No moderation issues flagged.</p>`;

  const actionItems = report.actionItems.length
    ? `<ol class="actions">${report.actionItems.map((a) => `<li>${esc(a)}</li>`).join("")}</ol>`
    : `<p class="muted">No action items.</p>`;

  const topComment = report.topComment
    ? `<blockquote class="top">“${esc(report.topComment.text.trim())}”<footer>${esc(
        report.topComment.author,
      )} · 👍 ${formatNum(report.topComment.likeCount)} · ${esc(
        shortDate(report.topComment.publishedAt),
      )}</footer></blockquote>`
    : "";

  const allComments = [...comments]
    .sort((a, b) => b.likeCount - a.likeCount)
    .map(htmlComment)
    .join("");

  const bar = (label: string, val: number, color: string) =>
    `<div class="srow"><span class="slabel">${label}</span><div class="track"><div class="fill" style="width:${Math.round(
      val,
    )}%;background:${color}"></div></div><span class="sval">${Math.round(val)}%</span></div>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Community AI — ${esc(video.title)}</title>
<style>
  :root{--bg:#f7f7f8;--card:#fff;--fg:#0a0a0b;--muted:#71717a;--border:#e4e4e7;--pill:#f4f4f5;--primary:#111113;--success:#16a34a;--danger:#dc2626;--radius:12px}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
  .wrap{max-width:960px;margin:0 auto;padding:32px 20px 80px}
  .brand{display:inline-flex;gap:8px;align-items:center;font-size:12px;color:var(--muted);border:1px solid var(--border);background:#fff;border-radius:999px;padding:4px 10px;margin-bottom:16px}
  h1{font-size:22px;margin:0 0 4px}
  h2{font-size:16px;margin:28px 0 12px}
  h3{font-size:15px;margin:0}
  a{color:inherit}
  .muted{color:var(--muted)}
  .card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:18px;margin-bottom:14px;box-shadow:0 1px 2px rgba(0,0,0,.03)}
  .card-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}
  .head{display:flex;gap:16px;flex-wrap:wrap;align-items:flex-start}
  .thumb{width:260px;max-width:100%;border-radius:10px;border:1px solid var(--border);display:block}
  .badge{display:inline-block;background:var(--pill);color:#3f3f46;border-radius:6px;padding:2px 8px;font-size:12px;margin:4px 6px 0 0}
  .metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:16px 0}
  @media(max-width:720px){.metrics{grid-template-columns:repeat(3,1fr)}.grid2{grid-template-columns:1fr!important}.sections{grid-template-columns:1fr!important}}
  .metric{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:12px}
  .metric .l{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}
  .metric .v{font-size:20px;font-weight:600;margin-top:4px}
  .grid2{display:grid;grid-template-columns:2fr 1fr;gap:14px}
  .pill{background:var(--pill);color:#3f3f46;border-radius:6px;padding:2px 8px;font-size:12px;white-space:nowrap}
  .srow{display:flex;align-items:center;gap:8px;margin:6px 0;font-size:13px}
  .slabel{width:64px;color:var(--muted)}
  .track{flex:1;height:8px;background:var(--pill);border-radius:999px;overflow:hidden}
  .fill{height:100%;border-radius:999px}
  .sval{width:40px;text-align:right;color:var(--muted)}
  details.acc{border-bottom:1px solid var(--border)}
  details.acc:last-child{border-bottom:0}
  details.acc>summary{list-style:none;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 2px;font-weight:500}
  details.acc>summary::-webkit-details-marker{display:none}
  details.acc>summary::after{content:"▸";color:var(--muted);transition:transform .15s;margin-left:auto}
  details.acc[open]>summary::after{transform:rotate(90deg)}
  .acc-label{overflow:hidden;text-overflow:ellipsis}
  .acc-label.danger{color:var(--danger);font-weight:600}
  .cm-list{list-style:none;margin:0 0 12px;padding:0;display:flex;flex-direction:column;gap:8px}
  .cm{background:#fafafa;border:1px solid var(--border);border-radius:8px;padding:8px 10px}
  .cm-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:3px}
  .cm-author{font-weight:600;font-size:13px}
  .cm-meta{color:var(--muted);font-size:12px;white-space:nowrap}
  .cm-text{font-size:13px;white-space:pre-wrap}
  .sub{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin:8px 0 6px}
  .chips{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:6px}
  .chip{border:1px solid var(--border);background:#fafafa;border-radius:999px;padding:3px 10px;font-size:12px}
  .top{margin:12px 0 0;background:#fafafa;border:1px solid var(--border);border-radius:8px;padding:10px}
  .top footer{margin-top:6px;color:var(--muted);font-size:12px}
  .actions{margin:0;padding-left:20px}
  .actions li{margin:4px 0}
  .sections{display:grid;grid-template-columns:1fr 1fr;gap:14px}
  footer.foot{margin-top:32px;color:var(--muted);font-size:12px;text-align:center}
</style>
</head>
<body>
<div class="wrap">
  <div class="brand">Community AI · YouTube Community Intelligence</div>
  <div class="card">
    <div class="head">
      ${video.thumbnail ? `<a href="${esc(video.url)}"><img class="thumb" src="${esc(video.thumbnail)}" alt="" /></a>` : ""}
      <div style="flex:1;min-width:220px">
        <div class="muted" style="font-size:12px">${esc(video.channelTitle)} · ${esc(shortDate(video.publishedAt))}</div>
        <h1><a href="${esc(video.url)}">${esc(video.title)}</a></h1>
        <div>
          <span class="badge">${formatNum(video.viewCount)} views</span>
          <span class="badge">${formatNum(video.likeCount)} likes</span>
          <span class="badge">${formatNum(report.totalComments)} comments analyzed</span>
        </div>
      </div>
    </div>
  </div>

  <div class="metrics">
    <div class="metric"><div class="l">Comments</div><div class="v">${formatNum(report.totalComments)}</div></div>
    <div class="metric"><div class="l">Replies</div><div class="v">${formatNum(report.totalReplies)}</div></div>
    <div class="metric"><div class="l">Views</div><div class="v">${formatNum(video.viewCount)}</div></div>
    <div class="metric"><div class="l">Positive</div><div class="v">${Math.round(s.positivePct)}%</div></div>
    <div class="metric"><div class="l">Negative</div><div class="v">${Math.round(s.negativePct)}%</div></div>
    <div class="metric"><div class="l">Confidence</div><div class="v">${Math.round(report.confidence * 100)}%</div></div>
  </div>

  <div class="grid2">
    <div class="card">
      <div class="card-head"><h3>Executive Summary</h3></div>
      <p>${esc(report.summary)}</p>
      ${topComment ? `<div class="sub">Top Comment</div>${topComment}` : ""}
    </div>
    <div class="card">
      <div class="card-head"><h3>Sentiment</h3><span class="pill">${esc(s.label)}</span></div>
      ${bar("Positive", s.positivePct, "var(--success)")}
      ${bar("Neutral", s.neutralPct, "#a1a1aa")}
      ${bar("Negative", s.negativePct, "var(--danger)")}
    </div>
  </div>

  <div class="card">
    <div class="card-head"><h3>Most Requested Future Episodes</h3></div>
    ${futureEpisodes}
  </div>

  <h2>Feedback by Theme</h2>
  <div class="sections">
    ${themeCard("Positive Feedback", report.positiveFeedback)}
    ${themeCard("Criticism", report.criticism)}
    ${themeCard("Episode Requests", report.episodeRequests)}
    ${themeCard("Host Feedback", report.hostFeedback)}
    ${themeCard("Editing Feedback", report.editingFeedback)}
    ${themeCard("Sponsor Feedback", report.sponsorFeedback)}
    ${themeCard("Thumbnail Feedback", report.thumbnailFeedback)}
    ${themeCard("Title Feedback", report.titleFeedback)}
    ${themeCard("Recurring Topics", report.recurringTopics)}
    <section class="card">
      <div class="card-head"><h3>Moderation Issues</h3></div>
      ${moderation}
    </section>
  </div>

  <div class="card">
    <div class="card-head"><h3>Action Items</h3></div>
    ${actionItems}
  </div>

  <div class="card">
    <details class="acc">
      <summary><span class="acc-label">Full Comment Database</span><span class="pill">${formatNum(comments.length)}</span></summary>
      <ul class="cm-list">${allComments}</ul>
    </details>
  </div>

  <footer class="foot">Generated by Community AI · ${esc(new Date().toISOString().slice(0, 10))}</footer>
</div>
</body>
</html>`;
}

export function exportAs(
  format: ExportFormat,
  payload: ExportPayload,
): { content: string; mime: string; filename: string } {
  const slug =
    payload.video.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 50) || "report";
  switch (format) {
    case "html":
      return { content: toHtml(payload), mime: "text/html", filename: `${slug}.html` };
    case "markdown":
      return { content: toMarkdown(payload), mime: "text/markdown", filename: `${slug}.md` };
    case "txt":
      return { content: toTxt(payload), mime: "text/plain", filename: `${slug}.txt` };
    case "json":
      return { content: toJson(payload), mime: "application/json", filename: `${slug}.json` };
    case "csv":
      return { content: toCsv(payload), mime: "text/csv", filename: `${slug}-comments.csv` };
    case "sheets":
      return {
        content: `${SHEETS_HEADER}\n${toSheetsRow(payload)}`,
        mime: "text/tab-separated-values",
        filename: `${slug}.tsv`,
      };
  }
}
